### ISSUE TITLE
Fail with Uncaught TypeError: data.replace(...).matchAll(...)[Symbol.iterator] is not a function

### ISSUE THREAD

**Issue by afreidz** [ghaiklor/icecast-parser#137]
```1) RadioParser
       Should properly emit metadata from Icecast:
     Uncaught TypeError: data.replace(...).matchAll(...)[Symbol.iterator] is not a function
      at _parseMetadata (src/StreamReader.js:9:850)
      at StreamReader._onMetaData (src/StreamReader.js:9:6744)
      at _processData (src/StreamReader.js:9:3417)

**Comment by ghaiklor** [comment]
`matchAll` has support only starting from Node.js 12, see https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/matchAll
