### ISSUE TITLE
StreamReader.js .matchAll(...) error (Crashes app)

### ISSUE THREAD

**Issue by redimongo** [ghaiklor/icecast-parser#166]
```
/home/adstichrplayer/node_modules/icecast-parser/src/StreamReader.js:51
  const parts = [...data.replace(/\0*$/, '').matchAll(METADATA_REGEX)];
                                             ^

TypeError: data.replace(...).matchAll(...) is not a function or its return value is not iterable
```
I am wondering if something is not right here?

/home/adstichrplayer/node_modules/icecast-parser/src/StreamReader.js:51
  const parts = [...data.replace(/\0*$/, '').matchAll(METADATA_REGEX)];
                                             ^
```

TypeError: data.replace(...).matchAll(...) is not a function or its return value is not iterable
    at _parseMetadata (/home/adstichrplayer/node_modules/icecast-parser/src/StreamReader.js:51:46)
    at StreamReader._onMetaData (/home/adstichrplayer/node_modules/icecast-parser/src/StreamReader.js:232:27)
    at _processData (/home/adstichrplayer/node_modules/icecast-parser/src/StreamReader.js:102:8)
    at /home/adstichrplayer/node_modules/icecast-parser/src/StreamReader.js:123:14
    at /home/adstichrplayer/node_modules/icecast-parser/src/StreamReader.js:65:51
    at /home/adstichrplayer/node_modules/icecast-parser/src/StreamReader.js:126:24
    at /home/adstichrplayer/node_modules/icecast-parser/src/StreamReader.js:65:51
    at /home/adstichrplayer/node_modules/icecast-parser/src/StreamReader.js:126:24
    at /home/adstichrplayer/node_modules/icecast-parser/src/StreamReader.js:65:51
    at StreamReader._transform (/home/adstichrplayer/node_modules/icecast-parser/src/StreamReader.js:200:5)
    at StreamReader.Transform._read (_stream_transform.js:190:10)
    at StreamReader.Transform._write (_stream_transform.js:178:12)
    at doWrite (_stream_writable.js:415:12)
    at writeOrBuffer (_stream_writable.js:399:5)
    at StreamReader.Writable.write (_stream_writable.js:299:11)
    at IncomingMessage.ondata (_stream_readable.js:710:20)

```

**Comment by redimongo** [comment]
Seems the npm install had did not correctly download teh StreamReader.js - I copied it from this github and it works

**Comment by ghaiklor** [comment]
@redimongo `matchAll` works on latest Node.js version only. Current implementation in master adds a support for much older runtime version - https://github.com/ghaiklor/icecast-parser/pull/164 by @kostia1359 and I did not publish it to npm (yet)

**Comment by ghaiklor** [comment]
There will be a major update of the package that drops Node.js < 12 support. Node.js 14 will be LTS soon, so it makes little sense to support it anymore.

At the moment the implementation in `master` branch is already with `matchAll`. Older package versions must be used if you want to have support for Node.js < 12.
